apiVersion: networking.k8s.io/v1   # 프런트 cdn으로 배포하면 필요하니까 구성해둠
kind: Ingress  # ingress controller 설치 필요 
metadata:
  name: member-service-ingress
  namespace: user-namespace
spec:
  ingressClassName: nginx
  rules:
    - host: whowhomail.kro.kr
      http:
        paths:
          - path: /member/*
            pathType: Prefix
            backend:
              service:
                name: member-service
                port:
                  number: 80
  tls:
    - hosts: 
      - whowhomail.kro.kr
      secretName: tls-secret