apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization    # 묶어서 관리하기 
namespace: user-namespace
resources:
  - member-service/deployment.yaml
  - member-service/service.yaml
  - member-service/ingress.yaml
  - namespace.yaml
